version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: Running npm install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: Installing rollup
          command: sudo npm install --global rollup
      
      - run: 
          name: Creating /dist files with rollup
          command: rollup -c

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - deploy:
          name: Updating version num and publishing
          command: |
            if [[ "${CIRCLE_TAG}" =~ v[0-9]+(\.[0-9]+)* ]]; then
              npm --no-git-tag-version version ${CIRCLE_TAG:1}
              npm publish
            fi

      - store_artifacts:
          path: ~/repo/dist

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
